name: oneskyapp_inline_localization_tool
description: Write a Dart web app code lab
dependencies:
  browser: any
  polymer: ">=0.15.1 <0.16.0"
  paper_elements: '>=0.4.0 <0.5.0'
transformers:
- polymer:
    entry_points: web/translation_component/test.html
