name: oneskyapp_inline_localization_tool
description: Write a Dart web app code lab
version: 1.0.0
authors:
  - Vlastimil Dolejš <vlasta.dolejs@gmail.com>
homepage: https://github.com/DartPolymerHackatonPrague2014/oneskyapp.com-inline-localization-tool
dependencies:
  browser: ">=0.10.0+2 <0.11.0"
  polymer: ">=0.15.1 <0.16.0"
  paper_elements: '>=0.4.0 <0.5.0'
transformers:
- polymer:
    entry_points: web/translation_component/index.html
